source: docs
destination: build/docs
baseurl: /introducing-crystal

title: Introducing Crystal Programming Language
description: 『Introducing Crystal Programming Language』はプログラミング言語 Crystal の初心者〜中級者向け解説書です。
author: Crystal-JP
avatar: assets/images/avatar.png

theme: jekyll-theme-prologue

plugins:
  - asciidoctor-rouge
  - jekyll-asciidoc

asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    source-highlighter: rouge
    rouge-theme: base16
    rouge-css: style

sections: []
