version: 2.0

jobs:
  build:
    docker:
      - image: makenowjust/techbookfest-build:0.26.1-4
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            bundle install --path=vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Build
          command: bundle exec rake -j
      - store_artifacts:
          path: build
      - run:
          name: Lint
          command: bundle exec rake lint
      - run:
          name: Test
          command: bundle exec rake test
